// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyComoBlz6VHN0PBa5Ntl0G7Vy3t2iLSJ4A',
    appId: '1:226463894084:web:89fef87255e6de841f0a11',
    messagingSenderId: '226463894084',
    projectId: 'dhatnoon-rebuild',
    authDomain: 'dhatnoon-rebuild.firebaseapp.com',
    storageBucket: 'dhatnoon-rebuild.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjiE7771l_cSWsC2no6BElGObPM2vH0BE',
    appId: '1:226463894084:android:3699a011b89e22621f0a11',
    messagingSenderId: '226463894084',
    projectId: 'dhatnoon-rebuild',
    storageBucket: 'dhatnoon-rebuild.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFEajrQFSJEr625pHaKILZL40LqnxWqq8',
    appId: '1:226463894084:ios:e532ea7f7361fc411f0a11',
    messagingSenderId: '226463894084',
    projectId: 'dhatnoon-rebuild',
    storageBucket: 'dhatnoon-rebuild.appspot.com',
    iosClientId: '226463894084-q3agpl9lmakco0u5u83cqs7e7t1rcpqi.apps.googleusercontent.com',
    iosBundleId: 'com.example.dhatnoonV2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFEajrQFSJEr625pHaKILZL40LqnxWqq8',
    appId: '1:226463894084:ios:e532ea7f7361fc411f0a11',
    messagingSenderId: '226463894084',
    projectId: 'dhatnoon-rebuild',
    storageBucket: 'dhatnoon-rebuild.appspot.com',
    iosClientId: '226463894084-q3agpl9lmakco0u5u83cqs7e7t1rcpqi.apps.googleusercontent.com',
    iosBundleId: 'com.example.dhatnoonV2',
  );
}
